uw-midsun/strategy

.gitignore, auxloss/README.md, dynamics/README.md, optimization/README.md, routemodel/README.md, soc/README.md, solar/solar.py
Created a file structure for the repository
=> Filehousekeeping

solar/solar.py
I added comments to the solar model to clarify what physical systems each function describes. As well, I added simple linear integration to give an estimate of the total solar insolation.
=> Integration

requirements.txt
Added a requirements.txt file for the repo.
=> STRAT-36 added requirements.txt

soc/PackEfficiency.py, soc/SoCEstimation.py
SoC Algorithm based on the energy left in the pack. Not sure how we want to remove energy from the virtual pack, so made a basic function to do so.
Also a basic model for cell efficiency and associated ohmic power losses
Need to talk with Clarke about how this will fit with everything.
Note - not tested or anything, just programmed it in Notepad++
=> STRAT-17 - State of Charge Investigation Preliminary

optimization/car_model.py, optimization/generate_profile.py
Remove negative check in generate_profile.py + move universal constants (density of air and gravity) into universal class variables.
=> STRAT-60 Cleaning up generate profile and car model

solar/calculation-angles-cell.py, solar/solar.py
Added lines in solar.py to account for panel (cell) tilt angle.
Create file for **full cell** angle calculation to write to excel file.
=> Solar model

requirements.txt, routemodel/routes_elevs.py
Completed:
- request of route/elevation data and response from Bing Maps API
- parsing route data
- parsing elevation data
- main script
- writing data to csv files
Additional Notes:
- may want to add functionality of using addresses in API request, currently only coordinates work, and request functions assume user has entered coordinates
- may want to use Routes response coordinates (it interpolates more points) in getting Elevations data as these would be additional points; depends on how many points we would end up writing into the model, there are limits on the number of points you can query to both the route and elevation APIs
- Right now the API key is from my account that I've connected to Bing Maps Services, it looks like they allow 50,000 transactions per day (for an education …
=> Routes and Elevations model

soc/PackEfficiency.py, soc/tests/test_PackEfficiency.py
In the PackEfficiency class, self keyword added to the init function as it is referenced later. get_pack_ocv function added to be mocked out. Added brackets around quadratic formula denominator.
=> Add tests for the PackEfficiency class. 

README.md
Intended to help clarify some of the steps especially for anyone new to development.
=> Add some information to Getting Started section.

routemodel/data_retrieval/get_elevations.py, routemodel/data_retrieval/get_navigation.py, routemodel/tests/test_data_retrieval.py
pytest runs successfully from tests folder, routemodel folder, and strategy folder.
=> Fixed pytest error from relative file paths.

optimization/car_model.py
Added member variables and comparisons in each car_model method.
=> [STRAT-24] Set max and min within Car class. 

displays/README.md
Update for added parameters in calculate_SOC_values and updated names for both functions.
=> Update README in displays directory.

.github/workflows/python-app.yml, requirements.txt
Test in entire repository and individual directories. Not sure if we want to keep the defaults for linting. Running on 3.6 since we had issues with requirements for 3.8. Ignores routemodel since key not pushed up.
=> Create python-app.yml and change requirements.txt to include mock

README.md
Readme has been changed, added projects list, switched references to Emma from clarke, updated instructions with new guides that have been made, added some Python learning resources
=> Updating the readme for F2020

README.md
Here's my pull request - I added my name at the bottom. Let me know if this looks right!
=> onboarding test by Kristin

README.md
=> added my name (Janet) to the README for onboarding

.gitignore, README.md, routemodel/data_retrieval/config_example.py, routemodel/data_retrieval/get_elevations.py, routemodel/data_retrieval/get_navigation.py
=> Onboarding (final try)

README.md
Onboarding test (creating a pull request).
=> onboarding test

displays/dashboard/README.md, displays/dashboard/route.py
Wasn't running properly otherwise.
=> File path dashboard fix

optimization/car_model.py
=> [STRAT-90] Reject negative velocity

routemodel/data_retrieval/common.py, routemodel/data_retrieval/config_example.py, routemodel/data_retrieval/routes.py, routemodel/data_retrieval/speedlimits.py
Routes file completed, still working on tests, finalizing elevations with Krishna, finalizing speed limits as well.
PR for the heck of it. Only one file; rest will come soon. Elevs nearly done (in fact I think it is done but I have to review it and let Krishna know). Tests to be fixed up soon after. 
We will need to talk about the Speed Limits file cause I realized today that it works but is sort of very unoptimized. I have removed the class structure from it, didn't seem to need anything else... until I checked it out further today. It does return data as of now, so that's not the problem. Discuss sometime this week?
We aren't tracking these on the JIRA board which is why the ticket is STRAT-???.
=> [STRAT-114] Routes file finalized

soc/BatteryPower.py, soc/tests/test_BatteryPower.py
+ a test based on the data from can_messages.csv in the sample-battery-data branch
=> [STRAT-125] calculate power given current + voltage

weather_get.py
Added in the code (line 14-25) for all of the coordinates in the ASC2021 by making a nested list of all coordinates. Was wondering if there is a better way of calling each pair of coordinates (i.e. for loops) rather than manually indexing each and every point's lat and lon. Will add more code soon.
=> Weather coordinates

routemodel/data_retrieval/get_weather.py
- Set up code for energy calculation based on weather forecast API.
- The code is based on Solar team's code.
- Use One-call and Forecast for multiple days API from Openweather.
- Still in progress of editing.
- Goal: optimized model to obtain certain data from the API.
=> [STRAT-107] Add initial script for weather API

auxloss/aux_power_consumption.py, auxloss/tests/test_aux_power_consumption.py
Convenience method for something I did for Catherine. Not sure how it'll be adjusted by the future ticket but it's an interesting piece of functionality? 
Other than that, I think kWh just makes more sense as a unit unless anyone has strong feelings for the Ws -- our battery pack is stored in kWh too
=> Add typical total usage method and adjust unit to kWh

routemodel/routes/ASC2021/leaflet-test.py
- Adds `routemodel/routes/ASC2021/leaflet-test.py` for graphing ASC route
- App graphs route and allows editing of waypoints, when edited it saves to a output csv file
=> STRAT-179 - Graph ASC route

dynamics/wind_model.py, routemodel/data_retrieval/get_weather.py
Potential wind model to calculate drag force on the car given a CSV containing coordinate points of the route. Essentially the model is trying to get the wind speed parallel to the car’s direction of travel so you can just use the Drag Equation.
Main steps are as follows:
1. Generate a vector modelling the car’s direction
2. Call OpenWeather API to get wind data
3. Generate a wind vector modelling the wind’s direction based on the wind data in step 2
4. Solve for the component of the wind that is in the direction of the car’s motion 
5. Calculate drag force using the Drag Equation 
Output of the model is a data frame containing the drag force for the car travelling along a given two points. See example below:
Point 1                    Point 2  Drag Force (N)
0   (38.9300177, -95.6772808) …
=> [STRAT-171] Wind Feasibility Investigation
